services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.training
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data
      - ./ml:/app/ml
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    command: python ml/model_training.py

  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --backend-store-uri file:/mlflow/mlruns --host 0.0.0.0

  api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8001"
    volumes:
      - ./ml:/app/ml
    depends_on:
      - train
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app/dashboard
      - ./data:/app/data